# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 8,10,12,14,16 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/tidyverse

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Check this is working
          Rscript check_news.R 
      
